//
//  CustomSplashService.swift
//  SiberianViperExample
//
//  Created by Sergey Petrachkov on 05/05/2018.
//  Copyright (c) 2018 West Coast IT. All rights reserved.
//
//  This file was generated by the SergeyPetrachkov VIPER Xcode Templates so
//  you can apply VIPER architecture to your iOS projects.
//

import UIKit

protocol CustomSplashServiceProtocol: class {
  func doSomeWork()	
}

class CustomSplashService: CustomSplashServiceProtocol {
  func doSomeWork() {
  }
}
