//
//  CustomSplashRouter.swift
//  SiberianViperExample
//
//  Created by Sergey Petrachkov on 05/05/2018.
//  Copyright (c) 2018 West Coast IT. All rights reserved.
//
//  This file was generated by the Actonica VIPER Xcode Templates so
//  you can apply VIPER architecture to your iOS projects
//

import UIKit

protocol CustomSplashRoutingLogic {
  func showFeed(from view: UIViewController)
}


class CustomSplashRouter: CustomSplashRoutingLogic {
  // MARK: Routing
  func showFeed(from view: UIViewController) {
    let module = FeedAssembly.createModule(moduleIn: Feed.DataContext.ModuleIn())
    let wrappedModule = SVENavigationController(rootViewController: module)
    view.present(wrappedModule, animated: true, completion: nil)
  }
}
