//
//  CustomSplashEntities.swift
//  SiberianViperExample
//
//  Created by Sergey Petrachkov on 05/05/2018.
//  Copyright (c) 2018 West Coast IT. All rights reserved.
//
//  This file was generated by the SergeyPetrachkov VIPER Xcode Templates so
//  you can apply VIPER architecture to your iOS projects
//

import UIKit

enum CustomSplash {
  // MARK: - Use cases
  enum DataContext {
  	struct ModuleIn {
  	}
  	struct ModuleOut {
  	}
    struct Request {
    }
    struct Response {
    }
    struct ViewModel {
      init() {
      	
      }
    }
  }
}
