//
//  FeedService.swift
//  SiberianViperExample
//
//  Created by Sergey Petrachkov on 05/05/2018.
//  Copyright (c) 2018 West Coast IT. All rights reserved.
//
//  This file was generated by the SergeyPetrachkov VIPER Xcode Templates so
//  you can apply VIPER architecture to your iOS projects.
//

import UIKit
import SiberianVIPER
protocol FeedServiceProtocol: class {
  init(reporter: ErrorReporter?)
  func getItems(request: Feed.DataContext.Request,
                   success: @escaping ([FeedItem]) -> Void,
                   failure: @escaping (Error) -> Void)
}

class FeedService: FeedServiceProtocol {
  
  required init(reporter: ErrorReporter?) {
    self.errorReporter = reporter
  }
  
  let errorReporter: ErrorReporter?
  
  func getItems(request: Feed.DataContext.Request,
                   success: @escaping ([FeedItem]) -> Void,
                   failure: @escaping (Error) -> Void) {
    
    DispatchQueue.main.asyncAfter(deadline: .now() + 2.5, execute: {
      success([FeedItem(id: "111",
                        title: "Welcome to the example",
                        author: User(id: "1",
                                     firstname: "Sergey",
                                     lastname: "Petrachkov",
                                     description: "Software engineer"),
                        mediaInfo: MediaItem(id: "1254545", url: "https://pp.userapi.com/c639921/v639921945/509a5/nX__TG5bo4U.jpg")),
               FeedItem(id: "112",
                        title: "How are you doing?",
                        author: User(id: "2",
                                     firstname: "Sergey",
                                     lastname: "Petrachkov",
                                     description: "Musician"),
                        mediaInfo: nil)])
    })

  }
}
