//
//  FeedService.swift
//  SiberianViperExample
//
//  Created by Sergey Petrachkov on 05/05/2018.
//  Copyright (c) 2018 West Coast IT. All rights reserved.
//
//  This file was generated by the SergeyPetrachkov VIPER Xcode Templates so
//  you can apply VIPER architecture to your iOS projects.
//

import UIKit
import SiberianVIPER
protocol FeedServiceProtocol: class {
  init(reporter: ErrorReporter?)
  func getItems(request: Feed.DataContext.Request,
                   success: @escaping ([Any]) -> Void,
                   failure: @escaping (Error) -> Void)
}

class FeedService: FeedServiceProtocol {
  
  required init(reporter: ErrorReporter?) {
    self.errorReporter = reporter
  }
  
  let errorReporter: ErrorReporter?
  
  func getItems(request: Feed.DataContext.Request,
                   success: @escaping ([Any]) -> Void,
                   failure: @escaping (Error) -> Void) {

  }
}
