//
//  FeedCell.swift
//  SiberianViperExample
//
//  Created by Sergey Petrachkov on 05/05/2018.
//  Copyright (c) 2018 West Coast IT. All rights reserved.
//
//  This file was generated by the SergeyPetrachkov VIPER Xcode Templates so
//  you can apply VIPER architecture to your iOS projects
//

import Foundation
import UIKit
import SiberianVIPER

struct FeedModel: CollectionModelGeneric {
  static var anyViewType: UIView.Type {
    return FeedCell.self
  }
  
  let currentModel: Any
  
  func setup(view: FeedCell) {
    
  }
}
class FeedCell: UITableViewCell {
  
}
