//
//  FeedCell.swift
//  SiberianViperExample
//
//  Created by Sergey Petrachkov on 05/05/2018.
//  Copyright (c) 2018 West Coast IT. All rights reserved.
//
//  This file was generated by the SergeyPetrachkov VIPER Xcode Templates so
//  you can apply VIPER architecture to your iOS projects
//

import Foundation
import UIKit
import SiberianVIPER

struct FeedModel: CollectionModelGeneric {
  static var anyViewType: UIView.Type {
    return FeedCell.self
  }
  
  let currentModel: FeedItem
  
  func setup(view: FeedCell) {
    view.textLabel?.text = "\(self.currentModel.author.firstname) \(self.currentModel.author.description) - \(self.currentModel.title)"
  }
}
class FeedCell: UITableViewCell {
  override init(style: UITableViewCellStyle, reuseIdentifier: String?) {
    super.init(style: style, reuseIdentifier: reuseIdentifier)
    self.textLabel?.numberOfLines = 0
  }
  
  required init?(coder aDecoder: NSCoder) {
    fatalError("init(coder:) has not been implemented")
  }
}
